const $=id=>document.getElementById(id);
const api=async(url,opts={})=>{const res=await fetch(url,{headers:{"Content-Type":"application/json"},...opts});if(!res.ok)throw new Error((await res.json()).error||res.statusText);return res.json()};
let state={products:[],customers:[],suppliers:[],outwards:[]};
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");window.scrollTo(0,0)}
function table(rows,headers,editFn,delFn){if(!rows.length)return"<p>No records.</p>";return `<table><thead><tr>${headers.map(h=>`<th>${h.label}</th>`).join("")}<th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td>${esc(r[h.key])}</td>`).join("")}<td><button onclick="${editFn}(${r.id})">Edit</button><button onclick="${delFn}(${r.id})">Delete</button></td></tr>`).join("")}</tbody></table>`}
async function loadAll(){const health=await api("/api/health");state.products=await api("/api/products");state.customers=await api("/api/customers");state.suppliers=await api("/api/suppliers");state.outwards=await api("/api/outwards");const log=await api("/api/log");status.innerHTML=`<p><b>Server:</b> OK</p><p><b>Database:</b> ${esc(health.db)}</p><p><b>Products:</b> ${state.products.length} | <b>Customers:</b> ${state.customers.length} | <b>Suppliers:</b> ${state.suppliers.length} | <b>Outwards:</b> ${state.outwards.length}</p>`;$("log").innerHTML=log.map(l=>`<div>${esc(l.created_at)} — ${esc(l.action)} ${esc(l.table_name)} ${esc(l.detail)}</div>`).join("")||"<p>No activity yet.</p>";render()}
function render(){productList.innerHTML=table(state.products,[{key:"code",label:"Code"},{key:"description",label:"Description"},{key:"category",label:"Category"},{key:"location",label:"Location"},{key:"aisle_slot",label:"Aisle Slot"},{key:"haccp",label:"HACCP"},{key:"active",label:"Active"}],"editProduct","deleteProduct");customerList.innerHTML=table(state.customers,[{key:"code",label:"Code"},{key:"name",label:"Name / Branch"},{key:"address",label:"Address"},{key:"active",label:"Active"}],"editCustomer","deleteCustomer");supplierList.innerHTML=table(state.suppliers,[{key:"name",label:"Supplier"},{key:"active",label:"Active"},{key:"notes",label:"Notes"}],"editSupplier","deleteSupplier");outList.innerHTML=table(state.outwards,[{key:"packing_slip",label:"Packing Slip"},{key:"dispatch_date",label:"Dispatch Date"},{key:"customer_name",label:"Customer"},{key:"freight_detail",label:"Freight"}],"editOutPlaceholder","deleteOutPlaceholder")}
async function saveBasic(tableName, id, body){if(id)await api(`/api/${tableName}/${id}`,{method:"PUT",body:JSON.stringify(body)});else await api(`/api/${tableName}`,{method:"POST",body:JSON.stringify(body)});await loadAll()}
function clearProduct(){productForm.reset();productId.value="";productActive.value="Yes"}
async function importProductList(){if(!confirm("Import/update the product list into SQLite?"))return;const r=await api("/api/import-products-seed",{method:"POST"});await loadAll();alert(`Product import complete. Added ${r.added}, updated ${r.updated}. Total in file ${r.total}.`)}
productForm.onsubmit=async e=>{e.preventDefault();await saveBasic("products",productId.value,{code:productCode.value,description:productDesc.value,category:productCategory.value,location:productLocation.value,aisle_slot:productAisle.value,haccp:productHaccp.value,active:productActive.value,notes:productNotes.value});clearProduct()};
function editProduct(id){const r=state.products.find(x=>x.id===id);productId.value=r.id;productCode.value=r.code;productDesc.value=r.description;productCategory.value=r.category||"";productLocation.value=r.location||"";productAisle.value=r.aisle_slot||"";productHaccp.value=r.haccp;productActive.value=r.active;productNotes.value=r.notes;show("products")}
async function deleteProduct(id){if(confirm("Delete product?")){await api(`/api/products/${id}`,{method:"DELETE"});await loadAll()}}
function clearCustomer(){customerForm.reset();customerId.value="";customerActive.value="Yes"}
customerForm.onsubmit=async e=>{e.preventDefault();await saveBasic("customers",customerId.value,{code:customerCode.value,name:customerName.value,address:customerAddress.value,active:customerActive.value,notes:customerNotes.value});clearCustomer()};
function editCustomer(id){const r=state.customers.find(x=>x.id===id);customerId.value=r.id;customerCode.value=r.code;customerName.value=r.name;customerAddress.value=r.address;customerActive.value=r.active;customerNotes.value=r.notes;show("customers")}
async function deleteCustomer(id){if(confirm("Delete customer?")){await api(`/api/customers/${id}`,{method:"DELETE"});await loadAll()}}
function clearSupplier(){supplierForm.reset();supplierId.value="";supplierActive.value="Yes"}
supplierForm.onsubmit=async e=>{e.preventDefault();await saveBasic("suppliers",supplierId.value,{name:supplierName.value,active:supplierActive.value,notes:supplierNotes.value});clearSupplier()};
function editSupplier(id){const r=state.suppliers.find(x=>x.id===id);supplierId.value=r.id;supplierName.value=r.name;supplierActive.value=r.active;supplierNotes.value=r.notes;show("suppliers")}
async function deleteSupplier(id){if(confirm("Delete supplier?")){await api(`/api/suppliers/${id}`,{method:"DELETE"});await loadAll()}}
function addOutLine(){const n=outLineTemplate.content.firstElementChild.cloneNode(true);outLines.appendChild(n)}
function readOutLines(){return[...document.querySelectorAll("#outLines .line")].map(line=>({product_code:line.querySelector(".lineCode").value,product_description:line.querySelector(".lineDesc").value,qty_ordered:line.querySelector(".lineQtyOrdered").value,qty_dispatched:line.querySelector(".lineQtyDispatched").value,haccp:line.querySelector(".lineHaccp").value,batch:line.querySelector(".lineBatch").value})).filter(x=>x.product_code||x.product_description||x.qty_ordered||x.qty_dispatched||x.batch)}
outForm.onsubmit=async e=>{e.preventDefault();await api("/api/outwards",{method:"POST",body:JSON.stringify({packing_slip:outPackingSlip.value,dispatch_date:outDispatchDate.value||today(),customer_code:outCustomerCode.value,customer_name:outCustomerName.value,delivery_address:outDeliveryAddress.value,freight_detail:outFreightDetail.value,comments:outComments.value,lines:readOutLines()})});outForm.reset();outLines.innerHTML="";outDispatchDate.value=today();addOutLine();await loadAll();alert("Outwards saved to SQLite.")}
function editOutPlaceholder(){alert("Edit Outwards comes next.")}
function deleteOutPlaceholder(){alert("Delete Outwards comes next.")}
async function backup(){const r=await api("/api/backup",{method:"POST"});alert("Backup created:\\n"+r.file)}
outDispatchDate.value=today();addOutLine();loadAll().catch(e=>alert(e.message));
